from uuid import uuid4

from django.db import models
from django.utils import timezone


class MailLog(models.Model):
    """Audit log of every email send attempt.

    A record is written for each ``Email.send()`` call — both successful
    deliveries and failures — when ``SIMPLE_MAILER_LOG_EMAILS = True`` is
    set in Django settings. The full rendered content of the email is stored
    so that failed deliveries can be inspected or re-sent from Django admin.

    This model requires a database. See the README for setup instructions.
    """

    class Meta:
        verbose_name = "Mail Log"
        verbose_name_plural = "Mail Logs"

    #: Autogenerated UUID primary key.
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    #: When this log entry was created.
    created = models.DateTimeField(default=timezone.now, blank=True, null=True)

    #: When this log entry was last modified.
    modified = models.DateTimeField(default=timezone.now, blank=True, null=True)

    #: True if the email was delivered successfully; False on error.
    sent = models.BooleanField(default=False)

    #: Exception message if delivery failed; null on success.
    error = models.TextField(blank=True, null=True)

    #: Sender address — mirrors ``settings.DEFAULT_FROM_EMAIL`` at send time.
    sender = models.CharField(max_length=128, blank=True, null=True)

    #: List of recipient email addresses, stored as a JSON array.
    #: JSONField is used instead of a Postgres-specific ArrayField so the
    #: library works with any Django-supported database backend.
    recipients = models.JSONField(blank=True, null=True)

    #: Rendered subject line.
    #: max_length=998 matches the maximum header line length defined in
    #: RFC 2822 §2.1.1 and RFC 5322 §2.1.1 (998 characters excluding CRLF).
    subject = models.CharField(max_length=998, blank=True, null=True)

    #: Rendered plain-text body.
    txt_message = models.TextField(blank=True, null=True)

    #: Rendered HTML body.
    html_message = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.modified = timezone.now()
        super().save(*args, **kwargs)
